#!/usr/bin/env bash

set -euo pipefail
trap 'printf "Errore alla riga %s\n" "$LINENO" >&2' ERR

read -r -d '' DATI <<'EOF' || true
mvme2500 image ec-sde public tar
mvme2500 image ec-sre public tar
mvme2500 sdk ec-sdk public sh
mvme5100 image ec-sde public tar
mvme5100 image ec-sre public tar
mvme5100 sdk ec-sdk public sh
mvme6100 image ec-sde public tar
mvme6100 image ec-sre public tar
mvme6100 sdk ec-sdk public sh
mvme7100 image ec-sde public tar
mvme7100 image ec-sre public tar
mvme7100 sdk ec-sdk public sh
beaglebone image ec-sde public tar
beaglebone image ec-sde public wic
beaglebone image ec-sre public tar
beaglebone image ec-sre public wic
beaglebone sdk ec-sdk public sh
EOF

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    exec 3<<< "$DATI"

    while read -r -u 3 machine type image outputdir format; do
        export MACHINE="$machine"

        case "$type" in
            image)
                nice bitbake -k "$image" -c rootfs
                ;;
            sdk)
                ;;
            *)
                printf 'Type unknown: %s\n' "$type" >&2
                exit 1
                ;;
        esac
    done

    exec 3<&-
fi
