require conf/distro/voltumna.inc

DISTRO_NAME = "EC"
SDK_VENDOR = "-ecsdk"
TARGET_VENDOR = "-ec"

OLDEST_KERNEL = "6.12"
LINUXLIBCVERSION = "6.12"
PREFERRED_VERSION_virtual/kernel ?= "6.12%"
PREFERRED_VERSION_linux-libc-headers ?= "6.12%"

PREFERRED_VERSION_nativesdk-libgfortran = "${GCCVERSION}"

PREFERRED_VERSION_tango-idl = "6.0%"
PREFERRED_VERSION_nativesdk-tango-idl = "6.0%"
PREFERRED_VERSION_cpptango = "10.3%"
PREFERRED_VERSION_nativesdk-cpptango = "10.3%"
PREFERRED_VERSION_nativesdk-pogo = "9.10%"

# Necessary to add lapack
FORTRAN:forcevariable = ",fortran"
RUNTIMETARGET:append:pn-gcc-runtime = " libquadmath"

# Avoid build error
BBMASK:append = " \
		meta-ti/meta-ti-bsp/recipes-graphics/wayland/ \
		"
