require conf/distro/voltumna.inc

DISTRO_NAME = "EC"
SDK_VENDOR = "-ecsdk"
TARGET_VENDOR = "-ec"

# Avoid build error
BBMASK:append = " \
		meta-ti/meta-ti-bsp/recipes-graphics/wayland/ \
		"

OLDEST_KERNEL = "6.12"
LINUXLIBCVERSION = "6.12"
PREFERRED_VERSION_virtual/kernel ?= "6.12%"
PREFERRED_VERSION_linux-libc-headers ?= "6.12%"
PREFERRED_VERSION_linux-intel = "${PREFERRED_VERSION_virtual/kernel}"
PREFERRED_VERSION_linux-intel-rt = "${PREFERRED_VERSION_virtual/kernel}"

#PREFERRED_VERSION_libbpf = "1.3.0"

PREFERRED_VERSION_nativesdk-libgfortran = "${GCCVERSION}"

PREFERRED_VERSION_tango-idl = "6.0%"
PREFERRED_VERSION_nativesdk-tango-idl = "6.0%"
PREFERRED_VERSION_cpptango = "10.3%"
PREFERRED_VERSION_nativesdk-cpptango = "10.3%"
# PREFERRED_VERSION_python3-pytango = "10.1.%"
# PREFERRED_VERSION_nativesdk-python3-pytango = "10.1.%"
PREFERRED_VERSION_nativesdk-pogo = "9.10%"

# PREFERRED_VERSION_python3-setuptools-scm = "8.3.1"

# Necessary to add lapack
FORTRAN:forcevariable = ",fortran"
RUNTIMETARGET:append:pn-gcc-runtime = " libquadmath"
