require conf/distro/voltumna.conf

DISTRO_NAME = "EC"
SDK_VENDOR = "-ecsdk"
TARGET_VENDOR = "-ec"

# Necessary to add lapack
FORTRAN:forcevariable = ",fortran"
RUNTIMETARGET:append:pn-gcc-runtime = " libquadmath"
